# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            cbuhl
tagline:          'Photons, sailing and python.'
description:      'Danish physicist/engineer. Intermittent bright ideas.'
url:              https://cbuhl.github.io
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Christian Buhl Sørensen'
  url:            https://www.linkedin.com/in/cbuhl/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
#Change to motivate build
